version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name work5-webapp --s3-location s3://my-deploy-bucket-work5/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src